# Generated by Django 4.2 on 2023-04-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_contact_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
